# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./interima.sql:/docker-entrypoint-initdb.d/interima.sql:rw
      - mysql_data:/var/lib/mysql
    ports:
      - 11006:3306
volumes:
  mysql_data:
    driver: local